version: '3'
services:
# 1. 주키퍼 셋팅
  zookeeper:
    image: zookeeper:3.5.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_CLIENT_PORT: 2181

# 2. 카프카 확장
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1                                        # 브로커 고유 ID (클러스터 구성 시 필요)
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181                   # Zookeeper의 주소와 포트
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092    # 외부에서 접근할 때 사용하는 주소 (Docker에서는 localhost가 컨테이너 내부를 가리킬 수도 있어서 약간의 안전 장치 차원에서 권장)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092                 # 내부 브로커가 수신할 주소
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1                 # offset 저장용 internal 토픽 복제수. 단일 브로커면 1로 둔다
      ALLOW_PLAINTEXT_LISTENER: "yes"                           # Bitnami 이미지의 보안 정책 때문에 필수로 필요한 설정 (없으면 PLAINTEXT:// 리스너 자체가 비활성화되어 Kafka가 포트 바인딩에 실패 한다고 함)
    depends_on:                                                 # Zookeeper가 먼저 실행되도록 설정
      - zookeeper
